<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion><DefineConstants>ENABLE_PROFILER</DefineConstants><AssemblyName>PortProbe</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>../../ULTRAKILL.app/Contents/Resources/Data/Managed/Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../ULTRAKILL.app/Contents/Resources/Data/Managed/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>../../ULTRAKILL.app/Contents/Resources/Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>../../ULTRAKILL.app/Contents/Resources/Data/Managed/UnityEngine.PhysicsModule.dll</HintPath></Reference>
  <Reference Include="Unity.Collections"><HintPath>../../ULTRAKILL.app/Contents/Resources/Data/Managed/Unity.Collections.dll</HintPath></Reference>
<Reference Include="Unity.Mathematics"><HintPath>../../ULTRAKILL.app/Contents/Resources/Data/Managed/Unity.Mathematics.dll</HintPath></Reference>
<Reference Include="UnityEngine.ProfilerModule"><HintPath>../../ULTRAKILL.app/Contents/Resources/Data/Managed/UnityEngine.ProfilerModule.dll</HintPath></Reference></ItemGroup>
</Project>
